workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

stages:
  - .pre
  - download
  - build

sync:
  stage: .pre
  before_script:
    - git config --global user.name "${GITLAB_USER_NAME}"
    - git config --global user.email "${GITLAB_USER_EMAIL}"
  script:
    - git remote add github $REMOTE_REPOSITORY_URL
    - git checkout $CI_COMMIT_BRANCH
    - git status
    - git push -u github HEAD:$CI_COMMIT_BRANCH

download:
  stage: download
  image: curlimages/curl:7.85.0
  variables:
    TREESITTER_MAKEFILE_URL: 'https://github.com/nvim-treesitter/nvim-treesitter/raw/master/scripts/compile_parsers.makefile'
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - compile_parsers.makefile
  script: |
    [ -f compile_parsers.makefile ] || curl -LOJ ${TREESITTER_MAKEFILE_URL}

build:
  stage: build
  image: registry.gitlab.com/nickptails/tree-sitter
  variables:
    DEST_DIR: build
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - compile_parsers.makefile
  script:
    - make -f compile_parsers.makefile install
  artifacts:
    paths:
      - $DEST_DIR/parser.so
